name: Common Setup

on:
  workflow_call:
    inputs:
      task:
        description: 'The task to run (format, lint, build)'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Task
        run: |
          if [ "${{ inputs.task }}" == "format" ]; then
            npm run format
          elif [ "${{ inputs.task }}" == "lint" ]; then
            npm run lint
          elif [ "${{ inputs.task }}" == "build" ]; then
            npm run build
          else
            echo "Invalid task: ${{ inputs.task }}"
            exit 1
          fi