name: Pull Request Workflow
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest
    uses: ./.github/workflows/common-setup.yaml
    with:
      task: format

  lint:
    name: Linting
    runs-on: ubuntu-latest
    uses: ./.github/workflows/common-setup.yaml
    with:
      task: lint

  build:
    name: Build
    runs-on: ubuntu-latest
    uses: ./.github/workflows/common-setup.yaml
    with:
      task: build