name: Pull Request Workflow
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Call Common Setup
        uses: ./.github/workflows/common-setup.yaml

      - name: Check Formatting
        run: npm run format

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Call Common Setup
        uses: ./.github/workflows/common-setup.yaml

      - name: Run Linting
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Call Common Setup
        uses: ./.github/workflows/common-setup.yaml
        
      - name: Build Project
        run: npm run build
