name: Pull Request Workflow
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  common-setup:
    name: Common Setup
    runs-on: ubuntu-latest
    outputs:
      node_version: 20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

  format:
    name: Formatting
    needs: common-setup
    runs-on: ubuntu-latest

    steps:
      - name: Check Formatting
        run: npm run format

  lint:
    name: Linting
    needs: common-setup
    runs-on: ubuntu-latest

    steps:
      - name: Run Linting
        run: npm run lint

  build:
    name: Build
    needs: common-setup
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        run: npm run build
